name: "Terraform Multi-Cloud"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Formato: CLOUD_ENV (ej: AWS_DEV)'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_source_db_password: ${{ secrets.SOURCE_DB_PASSWORD }}
      TF_VAR_target_db_password: ${{ secrets.TARGET_DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Input
        id: parse
        run: |
          TARGET="${{ github.event.inputs.target }}"
          FOLDER=$(echo $TARGET | cut -d'_' -f1 | tr '[:upper:]' '[:lower:]')
          WORKSPACE=$(echo $TARGET | cut -d'_' -f2 | tr '[:upper:]' '[:lower:]')
          echo "folder=$FOLDER" >> $GITHUB_OUTPUT
          echo "workspace=$WORKSPACE" >> $GITHUB_OUTPUT
          # Seteamos la variable de entorno para que Terraform la lea
          echo "TF_VAR_environment=$WORKSPACE" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Execution
        run: |
          cd ${{ steps.parse.outputs.folder }}
          
          terraform init -reconfigure
          
          # 1. Selección de Workspace
          terraform workspace select -or-create ${{ steps.parse.outputs.workspace }}
          
          # 2. ADOPCIÓN DE RECURSOS (Import): 
          # En lugar de borrar, los importamos al estado si ya existen en AWS.
          # Esto evita el error de "AlreadyExists" y sincroniza el S3.
          echo "Sincronizando recursos existentes al estado..."
          terraform import module.dms_migration.aws_dms_replication_subnet_group.main sms-subnets-dev-new || true
          terraform import module.network.aws_db_subnet_group.database vpc-dev-db-group-fix || true
          
          # 3. Despliegue
          # Ahora Terraform verá que ya los tiene en el estado y no intentará recrearlos.
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan